[project]
name = "Zappy-IA"
version = "0.0.1"
dependencies = [
    "torch",
    "torchrl",
    "tqdm",
    "pytest",
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "scikit-learn",
    "seaborn",
    "jupyterlab",
    "papermill",
    "ruff",
    "ipywidgets",
    "tensorboard",
]
requires-python = ">= 3.9"
authors = [
    { name = "Ethan Charpentier", email = "ethan.charpentier@epitech.eu" },
    { name = "Thomas Boucard", email = "thomas.boucard@epitech.eu" },
]
description = "Reinforcement learning project for the Zappy"
readme = { file = "README.md", content-type = "text/markdown" }

[tool.setuptools]
py-modules = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
