name: Linter

on:
  pull_request:
    branches: [ "**" ]
    paths:
      - 'zappy/**'
      - '.github/workflows/linter.yml'
  push:
    branches: [ main ]
    paths:
      - 'zappy/**'
      - '.github/workflows/linter.yml'

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpp-linter:
    name: Check code style with clang-format and clang-tidy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends build-essential cmake clang-format-20 clang-tidy-20
      - name: Configure CMake
        run: cmake -S zappy -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPLATFORM=Off
      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '22'
          style: 'file'
          tidy-checks: ''
          database: 'build'
          ignore: '.github'
      - name: Fail fast if checks failed
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
