name: Makefile

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make:
    name: Check Makefile
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends build-essential cmake ccache
      - name: Run make
        run: |
          make
          make fclean
          make zappy_server
          make zappy_gui
          make zappy_ai
          make clean
